### ISSUE TITLE
Fails with "Error: invalid gzip header" on 40% of websites

### ISSUE THREAD

**Issue by Shnatsel** [adamreichold/zeptohttpc#3]
On some websites, e.g. http://notesinspanish.com, zeptohttpc v0.2.1 fails with the following error:

> Error: invalid gzip header

Firefox and curl work fine.

409,926 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/8e3285a45e1d657744a2697ced1bd8461031fb86/zeptohttpc-smoke-test/src/main.rs). Test tool output from all affected websites is too big to upload to Github, so here's a list of affected domains instead: [invalid-gzip-header-domains.txt.gz](https://github.com/adamreichold/zeptohttpc/files/6102451/invalid-gzip-header-domains.txt.gz)

**Comment by Shnatsel** [comment]
Github has keyboard shortcuts that are really easy to trigger accidentally. Sorry for the incomplete report, I'll fill in the issue details in about 10 minutes.

**Comment by adamreichold** [comment]
Thanks for testing. Decompression based on `Content-Encoding` was instantiated in the I/O stack were decompression based on `Transfer-Encoding` would be. Dropped the seldomly used `Transfer-Encoding` variant and fixed decompression to happen after chunk assembly.
