### ISSUE TITLE
fails with "Missing scheme" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [adamreichold/zeptohttpc#4]
On some websites, e.g. http://eatcdc.com, zeptohttpc v0.2.1 fails with the following error:

> Missing scheme

Firefox and curl work fine.

14723 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/8e3285a45e1d657744a2697ced1bd8461031fb86/zeptohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [zepto-missing-scheme.tar.gz](https://github.com/adamreichold/zeptohttpc/files/6102489/zepto-missing-scheme.tar.gz)

**Comment by adamreichold** [comment]
I think this was fixed by commit a63c22f084565b1fb36f2f96b2cabe62aa82f1ae which is part of version 0.3.0.
