### ISSUE TITLE
Fails with "corrupt deflate stream" on some websites

### ISSUE THREAD

**Issue by Shnatsel** [adamreichold/zeptohttpc#5]
On some websites, e.g. http://variancemagazine.com, zeptohttpc v0.2.1 fails with the following error:

> corrupt deflate stream

Firefox and curl work fine.

2344 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/8e3285a45e1d657744a2697ced1bd8461031fb86/zeptohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: 
[zepto-corrupt-deflate-stream.tar.gz](https://github.com/adamreichold/zeptohttpc/files/6102597/zepto-corrupt-deflate-stream.tar.gz)

Could be related to #3.

**Comment by adamreichold** [comment]
> Could be related to #3.

Seems to be unrelated, i.e. still fails using current `master` branch.

**Comment by adamreichold** [comment]
This was due to instantiating `flate2::bufread::DeflateDecoder` instead of `flate2::bufread::ZlibDecoder` for the deflate HTTP compression method.
