### ISSUE TITLE
Fails with "Invalid chunk size" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [adamreichold/zeptohttpc#7]
On some websites, e.g. http://skiperformance.com, zeptohttpc v0.2.1 fails with the following error:

> Invalid chunk size

Firefox and curl work fine.

335 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/8e3285a45e1d657744a2697ced1bd8461031fb86/zeptohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [zepto-cannot-chuck-the-chunk.tar.gz](https://github.com/adamreichold/zeptohttpc/files/6102905/zepto-cannot-chuck-the-chunk.tar.gz)

**Comment by adamreichold** [comment]
Cannot reproduce anymore, but I noticed that all headers indicated deflate compression, so this was most likely a combination of #3 and #5.
