### ISSUE TITLE
Fails with "Missing location" on some websites

### ISSUE THREAD

**Issue by Shnatsel** [adamreichold/zeptohttpc#8]
On some websites, e.g. http://macys.com, zeptohttpc v0.2.1 fails with the following error:

> Missing location

Firefox and curl work fine.

50 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/8e3285a45e1d657744a2697ced1bd8461031fb86/zeptohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [zepto-missing-location.tar.gz](https://github.com/adamreichold/zeptohttpc/files/6103186/zepto-missing-location.tar.gz)

**Comment by adamreichold** [comment]
Well these do indeed not set a `Location` header in their responses. `macys.com` does sent an error message in the body, but for example `cloudsee.net` sends an empty body anyway. Firefox and cURL just stop redirection in this case and from reading the HTTP/1.1 RFC this is correct as the server is not required to provide it, even though it should do so. Will follow their lead and stop redirection as well.
